#### Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [17]:
num = [10,20,30,40,50]
print('List Of Integers :',num)

List Of Integers : [10, 20, 30, 40, 50]


In [18]:
#append = used to add another integer

num.append(60)
print('Append :', num)

Append : [10, 20, 30, 40, 50, 60]


In [19]:
# extend = be can add multiple integers

num.extend([70,80,90])
print('Extend :', num)

Extend : [10, 20, 30, 40, 50, 60, 70, 80, 90]


In [20]:
# insert = be can add specific place with new integer

num.insert(2,25)
print('after insert :', num)

after insert : [10, 20, 25, 30, 40, 50, 60, 70, 80, 90]


In [21]:
# remove = can be a remove value

num.remove(30)
print('after remove :', num)

after remove : [10, 20, 25, 40, 50, 60, 70, 80, 90]


In [22]:
# pop = remove be a element with using index

num.pop(2)
print('after pop :', num)

after pop : [10, 20, 40, 50, 60, 70, 80, 90]


In [24]:
# index = to find integer with using index

num.index(40)
print('index :', num.index(40))

index : 2


In [25]:
# clear = To clear the All integer values

num.clear()
print('after clearing :', num)

after clearing : []


In [29]:
## sort = to sorting the data/integers

values = [10,15,20,50,70,35,25,65]
print('Before sort :',values)
values.sort()
print('After Sort :', values)

Before sort : [10, 15, 20, 50, 70, 35, 25, 65]
After Sort : [10, 15, 20, 25, 35, 50, 65, 70]


In [30]:
## reverse = reversing values

values = [10, 15, 20, 25, 35, 50, 65, 70]
print('Before reverse :',values)
values.reverse()
print('After reverse :', values)

## another way
rev = values[::-1]
print('another way for reverse :', rev)

Before reverse : [10, 15, 20, 25, 35, 50, 65, 70]
After reverse : [70, 65, 50, 35, 25, 20, 15, 10]
another way for reverse : [10, 15, 20, 25, 35, 50, 65, 70]


2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [32]:
students = ('X_student','Y_student','Z_student')
print('Student names :',students)
print(type(students))

Student names : ('X_student', 'Y_student', 'Z_student')
<class 'tuple'>


In [33]:
## trying to change second name
students[1] = "A_student"

## conclusion - 'tuple' object does not support item assignment

TypeError: 'tuple' object does not support item assignment

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [36]:
## set = automatically removes duplicates (unique values only)
num = {10,10,20,20,30,30,40,40}
print('set of values :',num)
print(type(num))

set of values : {40, 10, 20, 30}
<class 'set'>


4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [37]:
## Dictionary = used to store the data as key-value of pairs
dict = {'name':'X_name','age':25,'city':'Hyderabad'}
print('Dictionary Values:',dict)

Dictionary Values: {'name': 'X_name', 'age': 25, 'city': 'Hyderabad'}


In [38]:
dict.update(age = 35)
print('After updating age',dict )

After updating age {'name': 'X_name', 'age': 35, 'city': 'Hyderabad'}


In [39]:
dict.update(email = 'X_name@gmial.com')
print('After adding emial',dict )

After adding emial {'name': 'X_name', 'age': 35, 'city': 'Hyderabad', 'email': 'X_name@gmial.com'}


In [40]:
print('final output',dict)

final output {'name': 'X_name', 'age': 35, 'city': 'Hyderabad', 'email': 'X_name@gmial.com'}


5 . Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [41]:
age = int(input('Enter age : '))
if age >= 18:
    print('Eligible for Vote ')
else:
    print('Not Eligible for Vote ')

Enter age :  35


Eligible for Vote 


In [42]:
age = int(input('Enter age : '))
if age >= 18:
    print('Eligible for Vote ')
else:
    print('Not Eligible for Vote ')

Enter age :  17


Not Eligible for Vote 


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [43]:
marks = int(input('Enter Marks'))
if marks >= 90 and marks <=100:
    print('Grade A')
elif marks >= 75 and marks <=89:
    print('Grade B')
elif marks >= 50 and marks <=74:
    print ('Grade C')
elif marks >100:
    print('ERROR: enter max marks below 100 only')
else:
    print('FAIL')

Enter Marks 90


Grade A


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [47]:
num = int(input('Enter any Number'))
if num > 0 and num % 2 == 0:
    print('even number,positive')
elif num %2 >= 1 and num > 0:
    print ('Odd number & Positive')  
elif num == 0:
    print ('Zero')
else:
    print('Negetive')

Enter any Number -4


Negetive


In [48]:
num = int(input('Enter any Number'))
if num > 0 and num % 2 == 0:
    print('even number,positive')
elif num %2 >= 1 and num > 0:
    print ('Odd number & Positive')  
elif num == 0:
    print ('Zero')
else:
    print('Negetive')

Enter any Number 5


Odd number & Positive


In [49]:
num = int(input('Enter any Number'))
if num > 0 and num % 2 == 0:
    print('even number,positive')
elif num %2 >= 1 and num > 0:
    print ('Odd number & Positive')  
elif num == 0:
    print ('Zero')
else:
    print('Negetive')

Enter any Number 6


even number,positive


#### Section B: Numpy

8.	Create:
   - A scalar using np.array(5)
   - A 1D array with values 1 to 5
   - A 2D array (2x3) with values from 10 to 60 in steps of 10


In [51]:
import numpy as np
# Scalar

scalar = np.array(5)
print('Scalar :',scalar)                 

Scalar : 5


In [54]:
## A 1D array with values 1 to 5

num = [10,15,20,25,30]
one_D = np.array(num)
print('1D array:',one_D)

1D array: [10 15 20 25 30]


In [56]:
## A 2D array (2x3) with values from 10 to 60 in steps of 10

num_2 = [10,20,30],[40,50,60]
two_D = np.array(num_2)
print('2D array: ',two_D)

np.array(num_2)

2D array:  [[10 20 30]
 [40 50 60]]


array([[10, 20, 30],
       [40, 50, 60]])

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [57]:
four_D = np.random.randint(1,100, size=(4,4))
print(" 4x4 Numpy array :",four_D)

 4x4 Numpy array : [[40 78 25 91]
 [10 16 49 71]
 [21 78 72 37]
 [69 29 50 52]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [59]:
import numpy as np
import pandas as pd

arr_3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
df = pd.DataFrame(arr_3x3,columns=['A','B','C'],index=['e1','e2','e3'])
print('column & index')
print(df)

column & index
    A  B  C
e1  1  2  3
e2  4  5  6
e3  7  8  9


## Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [64]:
import pandas as pd

data = {'Name':['A_name','B_name','C_name','D_name','E_name','F_name','G_name','X_name','Y_name','Z_name'],
       'Age':[25, 30, 22, 28, 35, 40, 26, 32, 29, 45],
       'City':['SRH','RCB','CSK','MI','DD','KNR','Pune','GL','HYD','BNG'],
       'Salary':[30000, 45000, 28000, 50000, 60000,55000, 32000, 48000, 35000, 65000]}
df = pd.DataFrame(data)
print(df)

     Name  Age  City  Salary
0  A_name   25   SRH   30000
1  B_name   30   RCB   45000
2  C_name   22   CSK   28000
3  D_name   28    MI   50000
4  E_name   35    DD   60000
5  F_name   40   KNR   55000
6  G_name   26  Pune   32000
7  X_name   32    GL   48000
8  Y_name   29   HYD   35000
9  Z_name   45   BNG   65000


In [65]:
# use info = to get All info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [66]:
# use describe = works numerical only
df.describe()

Age        Salary
count  10.000000     10.000000
mean   31.200000  44800.000000
std     7.067924  13087.738112
min    22.000000  28000.000000
25%    26.500000  32750.000000
50%    29.500000  46500.000000
75%    34.250000  53750.000000
max    45.000000  65000.000000

In [67]:
# Select Name and City columns 
df[['Name','City']]

Name  City
0  A_name   SRH
1  B_name   RCB
2  C_name   CSK
3  D_name    MI
4  E_name    DD
5  F_name   KNR
6  G_name  Pune
7  X_name    GL
8  Y_name   HYD
9  Z_name   BNG

In [68]:
# Drop City Column

df.drop(['City'], axis=1)

Name  Age  Salary
0  A_name   25   30000
1  B_name   30   45000
2  C_name   22   28000
3  D_name   28   50000
4  E_name   35   60000
5  F_name   40   55000
6  G_name   26   32000
7  X_name   32   48000
8  Y_name   29   35000
9  Z_name   45   65000

In [72]:
## Fill any missing values in 'Salary' column with the mean

df.loc[[2, 5, 8], 'Salary'] = np.nan

In [73]:
df

Name  Age  City Salary
0  A_name   25   SRH  30000
1  B_name   30   RCB  45000
2  C_name   22   CSK    NaN
3  D_name   28    MI  50000
4  E_name   35    DD  60000
5  F_name   40   KNR    NaN
6  G_name   26  Pune  32000
7  X_name   32    GL  48000
8  Y_name   29   HYD    NaN
9  Z_name   45   BNG  65000

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  7 non-null      object
dtypes: int64(1), object(3)
memory usage: 452.0+ bytes


In [75]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

C:\Users\DELL\AppData\Local\Temp\ipykernel_18500\1235525370.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Salary'] = df['Salary'].fillna(df['Salary'].mean())


In [76]:
df

Name  Age  City        Salary
0  A_name   25   SRH  30000.000000
1  B_name   30   RCB  45000.000000
2  C_name   22   CSK  47142.857143
3  D_name   28    MI  50000.000000
4  E_name   35    DD  60000.000000
5  F_name   40   KNR  47142.857143
6  G_name   26  Pune  32000.000000
7  X_name   32    GL  48000.000000
8  Y_name   29   HYD  47142.857143
9  Z_name   45   BNG  65000.000000

In [77]:
data = {'Name':['A_name','B_name','C_name','D_name','E_name'],
       'Age':[25, 30, 22, 28, 35],
       'City':['SRH','RCB','SRH','MI','DD'],
       'Salary':[30000, 45000, 30000, 50000, 60000]}

In [78]:
import pandas as pd
df = pd.DataFrame(data)
df

Name  Age City  Salary
0  A_name   25  SRH   30000
1  B_name   30  RCB   45000
2  C_name   22  SRH   30000
3  D_name   28   MI   50000
4  E_name   35   DD   60000

In [79]:
df.drop_duplicates(subset=['City', 'Salary'])

Name  Age City  Salary
0  A_name   25  SRH   30000
1  B_name   30  RCB   45000
3  D_name   28   MI   50000
4  E_name   35   DD   60000